/**
 * Midi Control Change message types.
 */
export enum MidiControlChange {
  BankSelect = 0,
  ModulationWheel = 1,
  BreathController = 2,
  FootController = 4,
  PortamentoTile = 5,
  DataEntryMSB = 6,
  ChannelVolume = 7,
  Balance = 8,
  Pan = 10,
  ExpressionController = 11,
  EffectControl1 = 12,
  EffectControl2 = 13,
  GeneralPurposeController1 = 16,
  GeneralPurposeController2 = 17,
  GeneralPurposeController3 = 18,
  GeneralPurposeController4 = 19,

  // LSB section
  BankSelectLSB = 32,
  ModulationWheelLSB = 33,
  BreathControllerLSB = 34,
  FootControllerLSB = 36,
  PortamentoTileLSB = 37,
  DataEntryLSB = 38,
  ChannelVolumeLSB = 39,
  BalanceLSB = 40,
  PanLSB = 42,
  ExpressionControllerLSB = 43,

  EffectControl1LSB = 48,
  EffectControl2LSB = 49,
  EffectControl3LSB = 50,
  EffectControl4LSB = 51,

  // binary ones
  Sustain = 64,
  Portamento = 65,
  Sostenuto = 66,
  SoftPedal = 67,
  LegatoFootswitch = 68,
  Hold2 = 69,
  SoundController1 = 70,
  SoundController2 = 71,
  SoundController3 = 72,
  SoundController4 = 73,
  SoundController5 = 74,
  SoundController6 = 75,
  SoundController7 = 76,
  SoundController8 = 77,
  SoundController9 = 78,
  SoundController10 = 79,

  /* Alternative names for 70-78 */
  SoundVariation = 70,
  TimbreIntensitivity = 71,
  ReleaseTime = 72,
  AttackTime = 73,
  Brightness = 74,
  DecayTime = 75,
  VibratoRate = 76,
  VibratoDepth = 77,
  VibratoDelay = 78,
  GeneralPurposeController5 = 80,
  GeneralPurposeController6 = 81,
  GeneralPurposeController7 = 82,
  GeneralPurposeController8 = 83,
  PortamentoControl = 84,
  HighResolutionVelocityPrefix = 88,
  Effects1Depth = 91,
  Effects2Depth = 92,
  Effects3Depth = 93,
  Effects4Depth = 94,
  Effects5Depth = 95,
  DataIncrement = 96,
  DataDecrement = 97,
  NonRegisteredParameterNumberLSB = 98,
  NonRegisteredParameterNumberMSB = 99,
  RegisteredParameterNumberLSB = 100,
  RegisteredParameterNumberMSB = 101,

  // Channel Mode messages
  AllSoundsOff = 120,
  ResetAllControllers = 121,
  LocalControlOnOff = 122,
  AllNotesOff = 123,
  OmniModeOff = 124,
  OmniModeOn = 125,
  MonoModeOn = 126,
  PolyModeOn = 127,
}
